server:
  port: 8081

db:
  port: 3306
  name: sampledb_pro
  endpoint:
  username:
  password:

spring:
  datasource:
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}