server:
  port: 8081
  servlet:
    context-path: /r2s-mobile-store-api

db:
  port: 3306
  name: r2s_mobile_store_db
  endpoint: localhost
  username: root
  password: root

spring:
  datasource:
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

