server:
  port: 8080
  servlet:
    context-path: /r2s-mobile-store-api

db:
  port: 3306
  name: r2s_mobile_store_db
  endpoint: localhost
  username: root
<<<<<<< HEAD
  password: 444d50444d50
=======
  password: root
>>>>>>> 04426b21a1b8fe1d0f836f8b3710c875fec3abf6

spring:
  datasource:
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

# ADD 2023/10/05 KhanhBD START
  mail:
    host: smtp.gmail.com
    username: mobilestorer2s@gmail.com
    password: qafj jiyp kaof fyde
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
# ADD 2023/10/05 KhanhBD END
